name: Test Yq Action
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Get test
        id: get_value
        uses: ./
        with:
          cmd: yq '.test' examples/multiline-text.yaml
      - name: Multiline test
        run: echo "### It was [${{ steps.get_value.outputs.result }}]" >> $GITHUB_STEP_SUMMARY
      - name: Write inplace test
        id: lookupSdkVersion
        uses: ./
        with:
          cmd: yq -i '.b.c = 5' examples/sample.yaml
